import Link from 'next/link'
import './globals.css'
import { Controls } from './Controls'

export const metadata = {
	title: 'Web tutorial',
	description: 'Generated by Leona',
}

export default async function RootLayout({ children }) {
	const res = await fetch(process.env.NEXT_PUBLIC_API_URL + 'topics', {
		cache: 'no-store',
	})
	const topics = await res.json()

	return (
		<html>
			<body>
				<Link href="/">
					<h1>WEB</h1>
				</Link>

				<ol>
					{topics.map((topic) => {
						return (
							<li key={topic.id}>
								<Link href={`/read/${topic.id}`}>
									{topic.title}
								</Link>
							</li>
						)
					})}
				</ol>

				{children}

				<Controls />
			</body>
		</html>
	)
}
